name: Test ARM64 Bypass on Windows

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    runs-on: windows-11-arm
    steps:
      - name: Native CMD
        shell: pwsh
        run: |
          echo "Native shell reports:"
          echo $env:PROCESSOR_ARCHITECTURE
          echo "Naive CMD:"
          cmd.exe /c echo %PROCESSOR_ARCHITECTURE%
      - name: Direct CMD shell
        shell: cmd
        run: |
          echo "ARM CMD:"
          start /b /wait /machine arm64 cmd.exe "echo ^%PROCESSOR_ARCHITECTURE^% > tempfile.txt"
          ping 127.0.0.1 -n 6 > nul
          cat tempfile.txt

      - name: Setup Python
        shell: pwsh
        run: |
          curl -L -o micromamba.exe https://github.com/mamba-org/micromamba-releases/releases/download/1.5.10-0/micromamba-win-64
          echo "Create Python env on x64"
          ./micromamba create -c conda-forge --root-prefix ./.micromamba-root -p ./test-env --platform win-64 python
    
      - name: Execute Native ARM64 Test from Emulated Process
        shell: pwsh
        run: |
          echo "Python reports:"
          ./micromamba run --root-prefix ./.micromamba-root -p ./test-env python -c "import platform; print(platform.platform(), platform.machine())"
          echo "Naive CMD:"
          ./micromamba run --root-prefix ./.micromamba-root -p ./test-env python -c "import subprocess; subprocess.run(['cmd.exe', '/c', 'echo %PROCESSOR_ARCHITECTURE%'])"
          echo "ARM CMD via start:"
          ./micromamba run --root-prefix ./.micromamba-root -p ./test-env python -c "import subprocess, os; subprocess.run(['cmd.exe', '/c', 'start /b /wait /machine arm64 cmd.exe /c \"echo ^%PROCESSOR_ARCHITECTURE^% > tempfile2.txt\"'])"
          sleep 5
          cat tempfile2.txt
